services:
  - type: web
    name: backgammon-display
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
