const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||path.join(process.env.CODEX_HOME||path.join(require('node:os').homedir(),'.codex'),'skills/develop-web-game/node_modules/playwright'));
const OUT=process.env.BG_EVIDENCE||path.resolve(__dirname,'../../.visual-review/tabletop/backgammon/browser');fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report=[],errors=[];let c;
const check=(name,condition)=>{assert(condition,name);report.push({name,pass:true});};
try{c=await b.newContext({viewport:{width:600,height:600}});await c.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5202/')?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5202/?test=1');await p.waitForTimeout(180);
await p.keyboard.press('Enter');await p.waitForTimeout(80);check('Enter opens match setup',await p.locator('#match-setup').isVisible());
let visited=new Set();for(let i=0;i<10;i++){visited.add(await p.evaluate(()=>document.activeElement.dataset.action||document.activeElement.dataset.difficulty||document.activeElement.dataset.sound));await p.keyboard.press('ArrowDown');}check('all 10 setup controls reachable by D-pad',visited.size===10);
await p.locator('[data-sound=off]').click();await p.locator('[data-action=match-7]').click();await p.waitForTimeout(100);await p.screenshot({path:path.join(OUT,'board.png')});
check('opening double unavailable',await p.locator('#double-btn').isHidden());
await p.evaluate(()=>{const old=Math.random;Math.random=()=>.4;__bg.action('roll');Math.random=old;});check('opening tie shows two dice and waits for reroll',await p.evaluate(()=>__bg.state.game.opening&&__bg.state.game.phase==='need-roll'&&__bg.state.game.diceRolled.length===2&&__bg.state.game.diceRemaining.length===0));
await p.evaluate(()=>{let n=0;const old=Math.random;Math.random=()=>n++?0:.99;__bg.action('roll');Math.random=old;});await p.waitForTimeout(120);
check('higher ivory die starts using both numbers',await p.evaluate(()=>__bg.state.game.turn==='w'&&__bg.state.game.diceRemaining.join(',')==='6,1'));
await p.locator('.point.focusable').first().focus();await p.evaluate(()=>document.activeElement.click());await p.waitForTimeout(70);check('firmware focused-element click selects without pointer coordinates',await p.evaluate(()=>__bg.state.game.selected!==null));await p.screenshot({path:path.join(OUT,'selection.png')});
await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowDown');let found=false;for(let i=0;i<10;i++){if(await p.evaluate(()=>document.activeElement.id==='menu-btn')){found=true;break;}await p.keyboard.press('ArrowRight');}check('Menu reachable from selected board via D-pad',found);await p.keyboard.press('Enter');await p.waitForTimeout(100);check('Menu pauses',await p.locator('#pause').isVisible());
await p.locator('#pause [data-action=help]').click();for(let i=0;i<3;i++){await p.screenshot({path:path.join(OUT,`help-${i+1}.png`)});await p.locator('[data-action=help-next]').click();}check('help cycles every page',await p.locator('#help-page').innerText()==='1 / 3');await p.locator('[data-action=help-close]').click();await p.locator('[data-action=resume]').click();await p.waitForTimeout(100);
await p.locator('#cancel-btn').click();await p.waitForTimeout(70);check('cancel preserves dice and clears source',await p.evaluate(()=>__bg.state.game.selected===null&&__bg.state.game.diceRemaining.length===2));
await p.evaluate(()=>__bg.action('end-turn'));check('cannot skip playable dice',await p.evaluate(()=>__bg.state.game.turn==='w'));
const original=await p.evaluate(()=>JSON.stringify(__bg.state.game.board));await p.locator('.point.focusable').first().click();await p.waitForTimeout(50);await p.locator('.point.dest').first().click();await p.evaluate(()=>__bg.action('undo'));check('undo ignored during animation',await p.evaluate(()=>__bg.state.animating&&__bg.state.game.diceRemaining.length===1));await p.waitForTimeout(380);await p.locator('#undo-btn').click();check('undo restores exact board and dice',await p.evaluate(orig=>JSON.stringify(__bg.state.game.board)===orig&&__bg.state.game.diceRemaining.length===2,original));
for(let i=0;i<5;i++){if(await p.evaluate(()=>__bg.legal(__bg.state.game).length===0))break;await p.locator('.point.focusable').first().click();await p.waitForTimeout(40);const dest=p.locator('.point.dest').first();if(await dest.count())await dest.click();else await p.locator('#bear-btn').click();await p.waitForTimeout(350);}
await p.waitForTimeout(900);check('completed turn waits for explicit End Turn and allows Undo',await p.evaluate(()=>__bg.state.game.turn==='w')&&await p.locator('#end-btn').isVisible()&&await p.locator('#undo-btn').isVisible());await p.locator('#end-btn').click();await p.waitForTimeout(200);await p.locator('#menu-btn').click();const pauseState=await p.evaluate(()=>JSON.stringify(__bg.state.game));await p.waitForTimeout(1100);check('computer timers pause without mutating board',await p.evaluate(s=>JSON.stringify(__bg.state.game)===s,pauseState));
await p.locator('#pause [data-action=home]').click();await p.locator('#continue-btn').click();await p.waitForFunction(()=>__bg.state.game.turn==='w'&&__bg.state.game.phase==='need-roll',{},{timeout:15000});check('saved computer turn resumes and returns control',true);
// Restore a real pending AI double, accept, and complete its turn.
await p.evaluate(()=>{const g=__bg.newGame();g.opening=false;g.turn='b';g.cubeOffer={by:'b',value:2};__bg.set(g);__bg.save();__bg.action('home');});await p.locator('#continue-btn').click();await p.waitForTimeout(100);check('AI double offer survives Continue with response buttons',await p.locator('#accept-btn').isVisible());await p.locator('#accept-btn').click();await p.waitForFunction(()=>__bg.state.game.turn==='w'&&__bg.state.game.phase==='need-roll',{},{timeout:15000});check('accepted AI double resumes play and transfers ownership',await p.evaluate(()=>__bg.state.game.cube.value===2&&__bg.state.game.cube.owner==='w'));
await p.evaluate(()=>{const g=__bg.newGame();g.opening=false;g.turn='b';g.cube={value:2,owner:'b'};g.cubeOffer={by:'b',value:4};__bg.set(g,__bg.newMatch(7));});await p.locator('#decline-btn').click();check('declined double awards old cube once, not backgammon multiplier',await p.evaluate(()=>__bg.state.match.scoreB===2&&__bg.state.game.lastMultiplier===1));await p.reload();await p.waitForTimeout(180);await p.locator('#continue-btn').click();check('round-result score survives reload',await p.locator('#gameover').isVisible()&&await p.evaluate(()=>__bg.state.match.scoreB===2));
await p.evaluate(()=>{const g=__bg.newGame();g.opening=false;const m=__bg.newMatch(5);m.scoreW=1;__bg.set(g,m);__bg.result('w',true);});await p.locator('[data-action=next-round]').click();check('first one-away round is Crawford, no doubling',await p.evaluate(()=>__bg.state.game.crawford&&__bg.state.match.crawfordPlayed&&!__bg.canDouble(__bg.state.game,'w')));
await p.evaluate(()=>{const g=__bg.newGame();g.opening=false;g.cubeOffer={by:'w',value:2};__bg.set(g);__bg.save();__bg.action('home');});await p.locator('#continue-btn').click();await p.waitForTimeout(800);check('saved human double resolves without stalling',await p.evaluate(()=>!__bg.state.game.cubeOffer&&!__bg.state.aiBusy));
await p.evaluate(()=>__bg.start(7));await p.evaluate(()=>{let n=0,old=Math.random;Math.random=()=>n++?0:.99;__bg.action('roll');Math.random=old;});await p.waitForTimeout(100);await p.locator('.point.focusable').first().click();await p.waitForTimeout(50);await p.screenshot({path:path.join(OUT,'final-board-selected.png')});
for(const size of [{width:600,height:600},{width:1200,height:800}]){await p.setViewportSize(size);check(`${size.width}px app fits`,await p.evaluate(()=>{const r=document.querySelector('#app').getBoundingClientRect();return r.x>=-1&&r.y>=-1&&r.right<=document.documentElement.clientWidth+1&&r.bottom<=document.documentElement.clientHeight+1}));}
await c.close();
for(const width of [390,320]){const mobile=await b.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});await mobile.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5202/')?r.continue():r.abort());const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5202/?test=1');await p.waitForTimeout(160);await p.screenshot({path:path.join(OUT,`phone-${width}-home.png`)});await p.locator('#play-btn').tap();await p.locator('[data-action=match-1]').tap();await p.waitForTimeout(100);await p.screenshot({path:path.join(OUT,`phone-${width}-board.png`)});check(`${width}px real mobile board and menu fit`,await p.evaluate(()=>{const v=visualViewport,r=document.querySelector('#board').getBoundingClientRect(),m=document.querySelector('#menu-btn').getBoundingClientRect();return r.x>=0&&r.right<=v.width+.5&&m.right<=v.width&&m.height>=44}));await p.locator('#menu-btn').tap();await p.locator('#pause [data-action=help]').tap();await p.screenshot({path:path.join(OUT,`phone-${width}-help.png`)});check(`${width}px help back remains visible`,await p.evaluate(()=>{const r=document.querySelector('[data-action=help-close]').getBoundingClientRect();return r.y>=0&&r.bottom<=visualViewport.height}));await mobile.close();}
check('no browser runtime errors',errors.length===0);fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify({checks:report,errors},null,2));console.log(`${report.length} browser checks passed; ${OUT}`);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
